name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"

      - name: Install PHP dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librdkafka-dev
          sudo pecl install rdkafka
          echo "extension=rdkafka.so" | sudo tee -a /etc/php/8.3/cli/php.ini

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Validate PHP PSR
        run: composer run-script php-fixer
